version: '3'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./setup/graduates.csv:/tmp/graduates.csv
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    user: "1000"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    env_file:
      - .env
    user: "1000"